#!/usr/bin/env python3
# encoding: UTF-8
from enebootools.uiimage import UIImageInterface


iface = UIImageInterface()

if iface.parse_args(): # parsea los argumentos de entrada de consola
    # Si el parseo no devuelve error,
    iface.execute_actions() # ejecuta las acciones detectadas.