#!/usr/bin/env python2
# encoding: UTF-8
from enebootools.mergetool import MergeToolInterface


iface = MergeToolInterface()

if iface.parse_args():  # parsea los argumentos de entrada de consola
    # Si el parseo no devuelve error,
    iface.execute_actions()  # ejecuta las acciones detectadas.
